port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: trojan
    server: trojan3.udpgw.com
    port: 443
    type: trojan
    password: 561b1160-9886-11ed-99b7-1239d0255272
    skip-cert-verify: true
    sni: trouter2-azsc-uswe-3-a.trouter.teams.microsoft.com
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: trojan3.udpgw.com
    udp: true
  - name: sg-lb.vhax.net
    server: sg-lb.vhax.net
    port: 443
    type: vmess
    uuid: 6fea1649-425b-4092-bf53-29792152c925
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: trouter2-azsc-uswe-3-a.trouter.teams.microsoft.com
    network: ws
    ws-opts:
      path: /sshkit/otaku/63c0bc50d14b4/
      headers:
        Host: trouter2-azsc-uswe-3-a.trouter.teams.microsoft.com
    udp: true
  - name: sg1-v2ray.sshkit.org
    server: sg1-v2ray.sshkit.org
    port: 443
    type: vmess
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: teams.events.data.microsoft.com
    network: ws
    ws-opts:
      path: /sshkit/5343386642/63c0c0545e002/
      headers:
        Host: teams.events.data.microsoft.com
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - trojan
      - sg-lb.vhax.net
      - sg1-v2ray.sshkit.org
      - DIRECT
rule-providers:
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
  - RULE-SET,clash,REJECT
  - MATCH,FASTSSH-SSHKIT-HOWDY
