proxy-providers:
  Umum:
    type: http
    behavior: classical
    path: "./umum.yaml"
    url: https://fool.azurewebsites.net/get?vpn=vmess&format=clash&cc=SG&cdn=104.16.51.111
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Gaming:
    type: http
    behavior: classical
    path: "./gaming.yaml"
    url: https://fool.azurewebsites.net/get?vpn=vmess&format=clash&cc=SG&cdn=104.16.51.111
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: http
    behavior: classical
    path: "./sosmed.yaml"
    url: https://fool.azurewebsites.net/get?vpn=vmess&format=clash&cc=SG&cdn=104.16.51.111
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Streaming:
    type: http
    behavior: classical
    path: "./streaming.yaml"
    url: https://fool.azurewebsites.net/get?vpn=vmess&format=clash&cc=SG&cdn=104.16.51.111
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Umum
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Umum
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: ADS
  type: select
  proxies:
  - REJECT
  - Umum
  - Gaming
  - Sosmed
  - Streaming
- name: Gaming
  type: url-test
  disable-udp: false
  use:
  - Gaming
  url: http://www.gstatic.com/generate_204
  interval: '600'
- name: Sosmed
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Sosmed
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Streaming
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Streaming
  url: http://www.gstatic.com/generate_204
  interval: '300'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "./"
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  default-nameserver:
  - 8.8.8.8 #google
  - 8.8.4.4 #google
  - 1.1.1.1 #cloudflare
  - 1.0.0.1 #cloudflare
  - 9.9.9.9 #quaddns
  - 9.9.9.11 #quaddns
  - 192.168.170.28 #Tsel
  - 192.168.178.28 #Tsel
  - 192.168.130.28 #Tsel
  - 112.215.220.254 #Axis
  - 112.215.219.254 #Axis
  - 140.213.82.253 #Axis
  - 140.213.82.254 #Axis
  - 112.215.203.248 #Axis
  - 112.215.203.254 #Axis
  - 112.215.37.182 #XL
  - 112.215.37.183 #XL
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
  nameserver:
  - 8.8.8.8 #google
  - 8.8.4.4 #google
  - 1.1.1.1 #cloudflare
  - 1.0.0.1 #cloudflare
  - 9.9.9.9 #quaddns
  - 9.9.9.11 #quaddns
  - 192.168.170.28 #Tsel
  - 192.168.178.28 #Tsel
  - 192.168.130.28 #Tsel
  - 112.215.220.254 #Axis
  - 112.215.219.254 #Axis
  - 140.213.82.253 #Axis
  - 140.213.82.254 #Axis
  - 112.215.203.248 #Axis
  - 112.215.203.254 #Axis
  - 112.215.37.182 #XL
  - 112.215.37.183 #XL
  fallback:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.9
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- DST-PORT,22,DIRECT,no-resolve
- RULE-SET,rule_BlockAds,ADS
- RULE-SET,rule_reject,ADS
- RULE-SET,rule_basicads,ADS
- RULE-SET,rule_privacy,ADS
- RULE-SET,rule_porn,ADS
- RULE-SET,rule_nsfw,ADS
- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_Direct,DIRECT,no-resolve
- RULE-SET,rule_Speedtest,Umum
- RULE-SET,rule_Streaming,Streaming
- RULE-SET,rule_hbo,Streaming
- RULE-SET,rule_iqiyi,Streaming
- RULE-SET,rule_primevideo,Streaming
- RULE-SET,rule_twitch,Streaming
- RULE-SET,rule_Youtube,Streaming
- RULE-SET,rule_Sosmed,Sosmed
- RULE-SET,rule_line,Sosmed
- RULE-SET,rule_metaverse,Sosmed
- RULE-SET,rule_tiktok,Sosmed
- RULE-SET,rule_twitter,Sosmed
- RULE-SET,rule_telegram,Sosmed
- RULE-SET,rule_telegramcidr,Sosmed
- RULE-SET,rule_Gaming,Gaming
- RULE-SET,rule_discord,Gaming
- RULE-SET,rule_games,Gaming
- RULE-SET,rule_portgames,Gaming
- RULE-SET,rule_videoconferences,Streaming
- RULE-SET,rule_playstore,Umum
- DST-PORT,21,Umum
- DST-PORT,23,Umum
- DST-PORT,25,Umum
- DST-PORT,80,Umum
- DST-PORT,81,Umum
- DST-PORT,143,Umum
- DST-PORT,443,Umum
- DST-PORT,465,Umum
- DST-PORT,587,Umum
- DST-PORT,993,Umum
- DST-PORT,995,Umum
- DST-PORT,8000,Umum
- DST-PORT,8008,Umum
- DST-PORT,8080,Umum
- DST-PORT,8081,Umum
- DST-PORT,8090,Umum
- DST-PORT,8443,Umum
- DST-PORT,8888,Umum
- MATCH,Umum
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
tproxy-port: 7895
rule-providers:
  rule_Direct:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_direct.yaml
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_videoconferences:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_videoconferences.yaml"
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_videoconferences.yaml
    interval: 86400
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_sosmed.yaml
    interval: 86400
  rule_Streaming:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_streaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_streaming.yaml
    interval: 86400
  rule_Gaming:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_gaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_Speedtest:
    type: http
    behavior: domain
    url: https://rules.kr328.app/speedtest.yaml
    path: "./Rule Provider/rule_speedtest.yaml"
    interval: 86400
  rule_discord:
    type: http
    behavior: domain
    url: https://rules.kr328.app/discord.yaml
    path: "./Rule Provider/rule_discord.yaml"
    interval: 86400
  rule_BlockAds:
    type: http
    behavior: classical
    path: "./Rule Provider/rule_BlockAds.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400
  rule_reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./Rule Provider/rule_reject.yaml"
    interval: 86400
  rule_privacy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml
    path: "./Rule Provider/rule_privacy.yaml"
    interval: 86400
  rule_basicads:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_basicads.yaml
    path: "./Rule Provider/rule_basicads.yaml"
    interval: 86400
  rule_porn:
    type: http
    behavior: domain
    url: https://rules.kr328.app/category-porn.yaml
    path: "./Rule Provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_nsfw.yaml
    path: "./Rule Provider/rule_nsfw.yaml"
    interval: 86400
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: "./Rule Provider/rule_lancidr.yaml"
    interval: 86400
  rule_telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: "./Rule Provider/rule_telegramcidr.yaml"
    interval: 86400
  rule_telegram:
    type: http
    behavior: domain
    url: https://rules.kr328.app/telegram.yaml
    path: "./Rule Provider/rule_telegram.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://rules.kr328.app/category-games.yaml
    path: "./Rule Provider/rule_games.yaml"
    interval: 86400
  rule_hbo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/hbo.yaml
    path: "./Rule Provider/rule_hbo.yaml"
    interval: 86400
  rule_iqiyi:
    type: http
    behavior: domain
    url: https://rules.kr328.app/iqiyi.yaml
    path: "./Rule Provider/rule_iqiyi.yaml"
    interval: 86400
  rule_line:
    type: http
    behavior: domain
    url: https://rules.kr328.app/line.yaml
    path: "./Rule Provider/rule_line.yaml"
    interval: 86400
  rule_metaverse:
    type: http
    behavior: domain
    url: https://rules.kr328.app/facebook.yaml
    path: "./Rule Provider/rule_metaverse.yaml"
    interval: 86400
  rule_primevideo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/primevideo.yaml
    path: "./Rule Provider/rule_primevideo.yaml"
    interval: 86400
  rule_playstore:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/clash_for_android/main/rule_provider/rule_playstore.yaml
    path: "./Rule Provider/rule_playstore.yaml"
    interval: 86400
  rule_tiktok:
    type: http
    behavior: domain
    url: https://rules.kr328.app/tiktok.yaml
    path: "./Rule Provider/rule_tiktok.yaml"
    interval: 86400
  rule_twitch:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitch.yaml
    path: "./Rule Provider/rule_twitch.yaml"
    interval: 86400
  rule_twitter:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitter.yaml
    path: "./Rule Provider/rule_twitter.yaml"
    interval: 86400
  rule_Youtube:
    type: http
    behavior: domain
    url: https://rules.kr328.app/youtube.yaml
    path: "./Rule Provider/rule_Youtube.yaml"
    interval: 86400
ipv6: true
